import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="border-b bg-white sticky top-0 z-50">
          <div className="container mx-auto px-8 py-4 flex items-center justify-between">
            <a href="/" className="text-xl font-bold">
              Slipstream Labs
            </a>
            <div className="flex gap-6">
              <a href="/teams" className="text-sm hover:text-blue-600">
                Teams
              </a>
              <a href="/components" className="text-sm hover:text-blue-600">
                Components
              </a>
              <a href="/grand-prix" className="text-sm hover:text-blue-600">
                Calendar
              </a>
              <a href="/upgrades" className="text-sm hover:text-blue-600">
                Upgrades
              </a>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
