// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Prisma CLI / Migrate uses the direct (session-mode) connection on Supabase.
    // The pooled DATABASE_URL is used at runtime by the PrismaClient driver adapter.
    url: env("DIRECT_URL"),
  },
});
